### ISSUE TITLE
Parallel Task Run Issue

### ISSUE THREAD

**Issue by drkthomp** [SaintsRobotics/Dozer#2]
Issue for commit 7a0d7a1 on branch ParallelTask

Currently the parallel task branch runs main.java and seems to loop through the Parallel tasks's runTask with "no problem" according to print outs, however the actual tasks never run and the waiters eventually return false despite having no actual reason to do so. Not really sure what's going on. Here's the console that prints for debugging.  

[runtaskrun.txt](https://github.com/SaintsRobotics/Dozer/files/1658032/runtaskrun.txt)

**Comment by t2001s** [comment]
Bug fixed

**Comment by drkthomp** [comment]
Fixed with commit 9c5702a. no way for tasks to end, so went indefinitely
